#include "investigation.h"

Investigation::Investigation()
{

}
QString Investigation::get_stream(){
	QFile investigation("investigation.txt");

	investigation.open(QIODevice::WriteOnly | QIODevice::Text);
	QTextStream txtWriter(&investigation);
	txtWriter << "This file is generated by Qt\n";
	//qSetRealNumberPrecision()
	//out << "Result: " << qSetFieldWidth(10) << left << 3.14 << 2.7;

	// optional, as QFile destructor will already do it:
	investigation.close();
}
