#include "investigation.h"

namespace XemlUtilities{

	namespace ISA{

		Investigation::Investigation()
		{

		}
		void Investigation::get_stream(ItfDocument *_xemlDoc, QFile *_investigationfile){

			QTextStream My_investigation(_investigationfile);
			My_investigation << "hello world, I'm ben";







			//QFile investigation("investigation.txt");

			//investigation.open(QIODevice::WriteOnly | QIODevice::Text);
			//QTextStream txtWriter(&investigation);
			//txtWriter << "This file is generated by Qt\n";
			//qSetRealNumberPrecision()
			//out << "Result: " << qSetFieldWidth(10) << left << 3.14 << 2.7;

			// optional, as QFile destructor will already do it:
			//investigation.close();
		}
		QString Investigation::get_fileName(ItfDocument * _xemlDoc){
			QString ret("/i_"+static_cast<XemlDocument*>(_xemlDoc)->get_experiment_name());
			return ret;
		}
	}
}
